spring:
  datasource:
    url: jdbc:h2:mem:userlgn
    driver-class-name: org.h2.Driver
    username: renato
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    web:
      resources:
        static-locations: classpath:/static/